Convert to .NET 5
dotnet/try-convert pull request #310
Opened 2020-10-07 23:22 UTC by cartermp

fixes https://github.com/dotnet/try-convert/issues/309

- [x] Manual validation
- [x] Update netcoreapp3.1 regression tests
- [ ] Add .NET 5 regression tests

2020-10-07 23:26 UTC, cartermp commented on src/MSBuild.Abstractions/BaselineProject.cs
> +                return MSBuildFacts.Net5Windows;
I guess I should "future proof" this by appending `"-windows"` to the string?

2020-10-08 23:07 UTC, cartermp commented
alright @jmarolf this is done, please observe my crimes

2020-10-09 06:21 UTC, jmarolf commented on global.json
> -}
add back that newline

2020-10-09 06:24 UTC, jmarolf commented on src/MSBuild.Abstractions/MSBuild.Abstractions.csproj
> +    <TargetFramework>net5.0</TargetFramework>
This prevents us from running on the 3.1 runtime. I don't see a reason why someone should require the 5.0 runtime to do conversions. Can't we keep this as 3.1?

2020-10-09 06:26 UTC, jmarolf commented on src/try-convert/try-convert.csproj
> +    <TargetFramework>net5.0</TargetFramework>
As per other comment. can we keep this 3.1?

2020-10-09 06:28 UTC, jmarolf requested changes
I don't think this is the approach we want to take. You can upgrade projects to .NET 5 without requiring the .NET 5 runtime. I think we want to add some logic to determine the maximum TFM we can target with the installed SDK and then only offer that.

2020-10-09 16:45 UTC, cartermp commented
Is the 5.0 runtime actually required if something is a global tool?

2020-10-09 16:46 UTC, cartermp commented
> I think we want to add some logic to determine the maximum TFM we can target with the installed SDK and then only offer that

This is already done. The only time it will go to 5.0 right now is if you have a preview SDK installed and specify the `preview` flag.

2020-10-09 20:52 UTC, cartermp commented on src/MSBuild.Abstractions/BaselineProject.cs
> +                return MSBuildFacts.Net5Windows;
nah

2020-10-09 23:20 UTC, jmarolf approved these changes

2020-10-09 23:28 UTC, merged